update: update source
browserstack/xunit-browserstack pull request #7
Opened 2023-01-04 04:42 UTC by 07souravkunda

2023-01-25 13:54 UTC, kamal-kaur04 requested changes

2023-01-25 13:54 UTC, kamal-kaur04 commented on XUnit-BrowserStack/browserstack.yml
> +source: xunit-c#:sample-main:v1.0
```suggestion
source: xunit-c#:sample-sdk:v1.0
```

2023-03-10 08:39 UTC, Ankit098 approved these changes

2023-03-10 09:41 UTC, Ankit098 approved these changes

2023-03-10 10:24 UTC, merged